version: 2
jobs:
  test:
    working_directory: ~/react-tabllist
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: install-package
          command: yarn
      - save_cache:
        paths:
          - ./node_modules
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test-stylelint
          command: yarn lint
      - run:
          name: run-unit-test-and-uploading-reports
          command: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
        filters:
          branches:
            only:
              - master
