version: 2
jobs:
  build:
    branches:
      only:
        - master
      ignore:
        - gh-pages
    working_directory: ~/react-tabllist
    docker:
      - image: circleci/node:8.12.0
      - image: bash:4.4.19
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-package
          command: yarn
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test-stylelint
          command: yarn lint
      - run:
          name: run-unit-test-and-uploading-reports
          command: yarn test
      - run:
          name: chmod
          command: chmod +x build/scripts/pushDemo.sh
      - run:
          name: build-demo
          command: yarn ci-demo
