version: 2
jobs:
  build:
    working_directory: ~/react-tabllist
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-package
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          path:
            - ./node_modules
      - run:
          name: test-stylelint
          command: yarn lint
      - run:
          name: run-unit-test-and-uploading-reports
          command: yarn test
